---

- hosts: localhost
  connection: local
  vars:
    pip_install_packages:
      - name: docker
    docker_users:
      - vagrant
  tasks:
    - name: Install packages
      apt:
        name: '{{ item }}'
        state: latest
        update_cache: yes
        cache_valid_time: 3600
      loop:
        - "ansible"
        - "python-docker"
      # when: ansible_python_interpreter is undefined
      register: result
      changed_when: result.changed
      ignore_errors: yes
    - name: build container image
      docker_image:
        name: '{{ item.name }}'
        build:
          path: '{{ item.build_path }}'
        dockerfile: '{{ item.dockerfile }}'
        source: build
        state: present
      loop:
        - { name: 'core-api:vagrant', build_path: '/home/vagrant/app/api', dockerfile: '/home/vagrant/app/api/Dockerfile' }
        - { name: 'core-streamlit:vagrant', build_path: '/home/vagrant/app/dashboard', dockerfile: '/home/vagrant/app/dashboard/Dockerfile' }
        - { name: 'core-db:vagrant', build_path: '/home/vagrant/database', dockerfile: '/home/vagrant/database/Dockerfile' }
  roles:
    - '/home/vagrant/ansible/roles/geerlingguy.pip'
    - '/home/vagrant/ansible/roles/geerlingguy.docker'
